/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/Board.vue')['default']
    IconIcBaselineAddCircle: typeof import('~icons/ic/baseline-add-circle')['default']
    IconIcBaselineClose: typeof import('~icons/ic/baseline-close')['default']
    IconIcBaselineDraw: typeof import('~icons/ic/baseline-draw')['default']
    IconIcBaselineEditNote: typeof import('~icons/ic/baseline-edit-note')['default']
    IconMdiArrowRightThinCircleOutline: typeof import('~icons/mdi/arrow-right-thin-circle-outline')['default']
    IconMdiEraser: typeof import('~icons/mdi/eraser')['default']
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    IconMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    PostIt: typeof import('./src/components/PostIt.vue')['default']
  }
}
